server:
  port: 7010
  servlet:
    context-path: /api

spring:
  application:
    name: ns-bbs-rest
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    host: 124.221.124.200
    port: 6379
    password: 12345678
    # 单位 毫秒
    timeout: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1

dubbo:
  application:
    name: ns-bbs-rest
  registry:
    address: zookeeper://124.221.124.200:2181
    timeout: 60000
  protocol:
    name: dubbo
    port: 22001
  consumer:
    check: false
    timeout: 60000
  config-center:
    timeout: 60000
  provider:
    # 配了这个就可以抛出自定义异常（否则一直是RuntimeException）
    filter: -exception

# 自定义
interceptor:
  monitor:
    #是否启用监控
    status: true

cookie:
  # cookie写在对应的域名下
  domain: localhost.com

# 跨域配置，sso登录地址
crossOrigin:
  address: http://sso.localhost.com

# swagger打开
swagger:
  show: true

file:
  source:
    # 设定上传源文件允许的最大值（1024*1024*5=5M）
    length: 5242880
